spring.application.name=PaymentService

razorpay.key.id=rzp_test_QKMc862gNrpfFB
razorpay.key.secret=8cTg8SYDwoAMZzZCbNK65zG0

stripe.apiKey=sk_test_51UMNRDRiK8jJjpuALTUSBrRdRILLujstXxEkWhXeEtOJ4fW5IDz5CX4hguy1eM8u7vm1qLPUfCR2VArBy8N5jW4n007d1TQi4R